"""club

Revision ID: 14ec9b731e96
Revises: 6275db0e089a
Create Date: 2018-09-29 22:37:24.311099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ec9b731e96'
down_revision = '6275db0e089a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('club', sa.String(length=128), nullable=True))
    op.drop_column('user', 'vereniging')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('vereniging', sa.VARCHAR(length=128), nullable=True))
    op.drop_column('user', 'club')
    # ### end Alembic commands ###
