"""'permission'

Revision ID: a3cdeeda5d51
Revises: 04c83de9b4f9
Create Date: 2018-08-10 10:23:45.196598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cdeeda5d51'
down_revision = '04c83de9b4f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'access')
    # ### end Alembic commands ###
