"""vereniging

Revision ID: abb8603105d8
Revises: d2ef2260dd3a
Create Date: 2018-09-29 17:28:34.016112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb8603105d8'
down_revision = 'd2ef2260dd3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('vereniging', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'vereniging')
    # ### end Alembic commands ###
