"""opt

Revision ID: c05e643ad0ff
Revises: 2c212c919de6
Create Date: 2018-09-18 16:23:10.097811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c05e643ad0ff'
down_revision = '2c212c919de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('enroll', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'enroll')
    # ### end Alembic commands ###
